### ISSUE TITLE
Error on ../wp-login.php

### ISSUE THREAD

**Issue by 1tremer** [gretathemes/falcon#2]
Thank you very much for the good plugin. It makes my site faster. 

Since I activate it I receive the following error on the backend login page:

`Notice: wp_deregister_script wurde fehlerhaft aufgerufen. Deaktivieren Sie nicht das jquery Skript im Administrationsbereich. Um das Frontend-Theme zu erreichen, benutzen Sie den wp_enqueue_scripts Hook. Weitere Informationen: Debugging in WordPress (en) (Diese Meldung wurde in Version 3.6 hinzugefügt.) in /srv/www/htdocs/wordpress/wp-includes/functions.php on line 3897`

"wp_deregister_script wurde fehlerhaft aufgerufen" means that the script was leading with an error. 

What can I do?

Thanks in advance
Michael

**Comment by 1tremer** [comment]
Do you have any idea?

**Comment by gretathemes** [comment]
It was fixed in the version 1.2.3. Now the version is 1.2.4. Please update.

Sorry for the delay of reply. We missed this comment.
